export {
  IdentityError,
  createMemoryOwnerIdentityRepository,
  createOwnerIdentityCoordinator,
  type AuthenticatedPrincipal,
  type AuthenticationSession,
  type CredentialProofVerifier,
  type IdentityCommand,
  type IdentityErrorCode,
  type IdentityNoticeIntent,
  type IdentityPolicy,
  type IdentityResult,
  type OwnerIdentityCoordinator,
  type OwnerIdentityRepository,
  type OwnerIdentityRepositoryTransaction,
  type OwnerIdentityState,
  type CredentialRecord,
  type ProcessedIdentityCommand,
  type RecoveryAttempt,
  type SessionRecord,
  type VerifiedChannelChange,
  type PrincipalRole,
  type SessionVerifier,
} from './identity';

export {
  createMemoryWebAuthnStateStore,
  createWebAuthnCeremonyCoordinator,
  simpleWebAuthnServerAdapter,
  type WebAuthnAssertionProof,
  type WebAuthnCeremonyCoordinator,
  type WebAuthnCeremonyPurpose,
  type WebAuthnCeremonyRecord,
  type WebAuthnCredentialRecord,
  type WebAuthnServerAdapter,
  type WebAuthnStateStore,
} from './webauthn';
